### ISSUE TITLE
Word Tokenizer example

### ISSUE THREAD

**Issue by anjchang** [leonardr/olipy#5]
Hi Leonard, This is such a cool library. I'm trying to run the example from Readme.md
`WordTokenizer().tokenize(s)`
results in

> NameError: name 'WordTokenizer' is not defined

`from olipy.tokenizer import WordTokenizer`
results in 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "olipy/tokenizer.py", line 3, in <module>
    from textblob.base import BaseTokenizer
ImportError: No module named textblob.base

Am I missing a library?

**Comment by anjchang** [comment]
My mistake-- I was working in the wrong virtualenv.  All works now that tokenizer is imported correctly.
